import Pagination, { type Paginator } from '@/components/Pagination';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import AppLayout from '@/Layouts/AppLayout';
import { type Voucher } from '@/types/models';
import api from '@/lib/api';
import { Link, useSearchParams } from 'react-router-dom';
import { Plus, Search } from 'lucide-react';
import { useState, useEffect } from 'react';
import type { FormEventHandler } from 'react';
import { useQuery, keepPreviousData } from '@tanstack/react-query';

export default function VouchersIndex() {
    const [searchParams, setSearchParams] = useSearchParams();
    const page = parseInt(searchParams.get('page') || '1', 10);
    const search = searchParams.get('search') || '';

    const [searchInput, setSearchInput] = useState(search);

    useEffect(() => {
        setSearchInput(search);
    }, [search]);

    const { data: vouchersData, isLoading, isError } = useQuery<Paginator<Voucher>>({
        queryKey: ['vouchers', page, search],
        queryFn: async () => {
            const res = await api.get('/vouchers', {
                params: {
                    page,
                    search: search || undefined,
                },
            });
            return res.data;
        },
        placeholderData: keepPreviousData,
    });

    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        setSearchParams({ search: searchInput, page: '1' });
    };

    const handlePageChange = (newPage: number) => {
        setSearchParams({ search, page: String(newPage) });
    };

    return (
        <AppLayout title="Vouchers">
            <div className="mx-auto max-w-7xl space-y-5">
                <div className="flex items-center justify-between gap-4">
                    <form onSubmit={submit} className="flex flex-1 gap-2">
                        <Input
                            placeholder="Search by code or batch…"
                            value={searchInput}
                            onChange={(e) => setSearchInput(e.target.value)}
                            className="max-w-sm"
                        />
                        <Button type="submit" variant="secondary" className="cursor-pointer">
                            <Search className="size-4" />
                        </Button>
                    </form>
                    <Button asChild className="cursor-pointer">
                        <Link to="/vouchers/generate">
                            <Plus className="mr-1 size-4" /> Generate Vouchers
                        </Link>
                    </Button>
                </div>

                <Card>
                    <CardContent className="pt-6">
                        {isLoading ? (
                            <div className="flex h-48 items-center justify-center">
                                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
                            </div>
                        ) : isError || !vouchersData ? (
                            <div className="rounded-md bg-destructive/15 p-4 text-sm text-destructive text-center">
                                Failed to load vouchers.
                            </div>
                        ) : (
                            <>
                                <Table>
                                    <TableHeader>
                                        <TableRow>
                                            <TableHead className="w-12">S.N.</TableHead>
                                            <TableHead>Code</TableHead>
                                            <TableHead>Plan</TableHead>
                                            <TableHead>Type</TableHead>
                                            <TableHead>Batch</TableHead>
                                            <TableHead>Status</TableHead>
                                            <TableHead>Generated by</TableHead>
                                            <TableHead>Issued</TableHead>
                                        </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                        {vouchersData.data.length === 0 && (
                                            <TableRow>
                                                <TableCell colSpan={8} className="text-center text-muted-foreground">
                                                    No vouchers found.
                                                </TableCell>
                                            </TableRow>
                                        )}
                                        {vouchersData.data.map((v, i) => (
                                            <TableRow key={v.id}>
                                                <TableCell className="text-muted-foreground">
                                                    {(vouchersData.from ?? 0) + i}
                                                </TableCell>
                                                <TableCell className="font-mono font-medium">{v.code}</TableCell>
                                                <TableCell>{v.plan?.name ?? '—'}</TableCell>
                                                <TableCell>
                                                    <Badge variant="outline">{v.type}</Badge>
                                                </TableCell>
                                                <TableCell>{v.batch || '—'}</TableCell>
                                                <TableCell>
                                                    <Badge variant={v.status === '0' ? 'default' : 'secondary'}>
                                                        {v.status === '0' ? 'unused' : 'used'}
                                                    </Badge>
                                                </TableCell>
                                                <TableCell>{v.generated_by || '—'}</TableCell>
                                                <TableCell className="text-sm text-muted-foreground">
                                                    {v.issued_on || '—'}
                                                </TableCell>
                                            </TableRow>
                                        ))}
                                    </TableBody>
                                </Table>
                                <Pagination
                                    links={vouchersData.links}
                                    from={vouchersData.from}
                                    to={vouchersData.to}
                                    total={vouchersData.total}
                                    onPageChange={handlePageChange}
                                />
                            </>
                        )}
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
