server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    root /app/frontend/dist;
    index index.html;
    server_name _;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(api|sanctum)/ {
        root /app/public;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /storage/ {
        root /app/public;
        try_files $uri $uri/ =404;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        root /app/public;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_X_FORWARDED_PORT $server_port;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        include fastcgi_params;
        fastcgi_param HTTP_HOST $http_host;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    client_max_body_size 20M;
}
