#!/bin/bash
set -e

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
  CREATE USER IF NOT EXISTS '${RADIUS_DB_USER}'@'%' IDENTIFIED BY '${RADIUS_DB_PASS}';
  GRANT SELECT, INSERT, UPDATE, DELETE ON \`${MYSQL_DATABASE}\`.* TO '${RADIUS_DB_USER}'@'%';
  FLUSH PRIVILEGES;
EOSQL
