import Pagination, { type Paginator } from '@/components/Pagination';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import AppLayout from '@/Layouts/AppLayout';
import { type Voucher } from '@/types/models';
import { Head, Link, router } from '@inertiajs/react';
import { Plus, Search } from 'lucide-react';
import { FormEventHandler, useState } from 'react';

export default function VouchersIndex({
    vouchers,
    filters,
}: {
    vouchers: Paginator<Voucher>;
    filters: { search?: string; status?: string };
}) {
    const [search, setSearch] = useState(filters.search ?? '');

    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        router.get(route('vouchers.index'), { search }, { preserveState: true, replace: true });
    };

    return (
        <AppLayout title="Vouchers">
            <Head title="Vouchers" />
            <div className="mx-auto max-w-7xl space-y-5">
                <div className="flex items-center justify-between gap-4">
                    <form onSubmit={submit} className="flex flex-1 gap-2">
                        <Input
                            placeholder="Search by code or batch…"
                            value={search}
                            onChange={(e) => setSearch(e.target.value)}
                            className="max-w-sm"
                        />
                        <Button type="submit" variant="secondary">
                            <Search className="size-4" />
                        </Button>
                    </form>
                    <Button asChild>
                        <Link href={route('vouchers.create')}>
                            <Plus className="mr-1 size-4" /> Generate Vouchers
                        </Link>
                    </Button>
                </div>

                <Card>
                    <CardContent className="pt-6">
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead className="w-12">S.N.</TableHead>
                                    <TableHead>Code</TableHead>
                                    <TableHead>Plan</TableHead>
                                    <TableHead>Type</TableHead>
                                    <TableHead>Batch</TableHead>
                                    <TableHead>Status</TableHead>
                                    <TableHead>Generated by</TableHead>
                                    <TableHead>Issued</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {vouchers.data.length === 0 && (
                                    <TableRow>
                                        <TableCell colSpan={8} className="text-center text-muted-foreground">
                                            No vouchers found.
                                        </TableCell>
                                    </TableRow>
                                )}
                                {vouchers.data.map((v, i) => (
                                    <TableRow key={v.id}>
                                        <TableCell className="text-muted-foreground">
                                            {(vouchers.from ?? 0) + i}
                                        </TableCell>
                                        <TableCell className="font-mono font-medium">{v.code}</TableCell>
                                        <TableCell>{v.plan?.name ?? '—'}</TableCell>
                                        <TableCell>
                                            <Badge variant="outline">{v.type}</Badge>
                                        </TableCell>
                                        <TableCell>{v.batch}</TableCell>
                                        <TableCell>
                                            <Badge variant={v.status === '0' ? 'default' : 'secondary'}>
                                                {v.status === '0' ? 'unused' : 'used'}
                                            </Badge>
                                        </TableCell>
                                        <TableCell>{v.generated_by}</TableCell>
                                        <TableCell className="text-sm text-muted-foreground">
                                            {v.issued_on}
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                        <Pagination links={vouchers.links} from={vouchers.from} to={vouchers.to} total={vouchers.total} />
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
